export const nationality = [
    { label: 'Afghanistan', key: 'afghanistan' },
    { label: 'Albania', key: 'albania' },
    { label: 'Algeria', key: 'algeria' },
    { label: 'Andorra', key: 'andorra' },
    { label: 'Angola', key: 'angola' },
    { label: 'Argentina', key: 'argentina' },
    { label: 'Armenia', key: 'armenia' },
    { label: 'Australia', key: 'australia' },
    { label: 'Austria', key: 'austria' },
    { label: 'Azerbaijan', key: 'azerbaijan' },
    { label: 'Bahamas', key: 'bahamas' },
    { label: 'Bahrain', key: 'bahrain' },
    { label: 'Bangladesh', key: 'bangladesh' },
    { label: 'Barbados', key: 'barbados' },
    { label: 'Belarus', key: 'belarus' },
    { label: 'Belgium', key: 'belgium' },
    { label: 'Belize', key: 'belize' },
    { label: 'Benin', key: 'benin' },
    { label: 'Bhutan', key: 'bhutan' },
    { label: 'Bolivia', key: 'bolivia' },
    { label: 'Bosnia and Herzegovina', key: 'bosnia-and-herzegovina' },
    { label: 'Botswana', key: 'botswana' },
    { label: 'Brazil', key: 'brazil' },
    { label: 'Brunei', key: 'brunei' },
    { label: 'Bulgaria', key: 'bulgaria' },
    { label: 'Burkina Faso', key: 'burkina-faso' },
    { label: 'Burundi', key: 'burundi' },
    { label: 'Cabo Verde', key: 'cabo-verde' },
    { label: 'Cambodia', key: 'cambodia' },
    { label: 'Cameroon', key: 'cameroon' },
    { label: 'Canada', key: 'canada' },
    { label: 'Central African Republic', key: 'central-african-republic' },
    { label: 'Chad', key: 'chad' },
    { label: 'Chile', key: 'chile' },
    { label: 'China', key: 'china' },
    { label: 'Colombia', key: 'colombia' },
    { label: 'Comoros', key: 'comoros' },
    { label: 'Congo (Congo-Brazzaville)', key: 'congo' },
    { label: 'Costa Rica', key: 'costa-rica' },
    { label: 'Croatia', key: 'croatia' },
    { label: 'Cuba', key: 'cuba' },
    { label: 'Cyprus', key: 'cyprus' },
    { label: 'Czechia (Czech Republic)', key: 'czechia' },
    { label: 'Denmark', key: 'denmark' },
    { label: 'Djibouti', key: 'djibouti' },
    { label: 'Dominica', key: 'dominica' },
    { label: 'Dominican Republic', key: 'dominican-republic' },
    { label: 'Ecuador', key: 'ecuador' },
    { label: 'Egypt', key: 'egypt' },
    { label: 'El Salvador', key: 'el-salvador' },
    { label: 'Equatorial Guinea', key: 'equatorial-guinea' },
    { label: 'Eritrea', key: 'eritrea' },
    { label: 'Estonia', key: 'estonia' },
    { label: 'Eswatini (fmr. "Swaziland")', key: 'eswatini' },
    { label: 'Ethiopia', key: 'ethiopia' },
    { label: 'Fiji', key: 'fiji' },
    { label: 'Finland', key: 'finland' },
    { label: 'France', key: 'france' },
    { label: 'Gabon', key: 'gabon' },
    { label: 'Gambia', key: 'gambia' },
    { label: 'Georgia', key: 'georgia' },
    { label: 'Germany', key: 'germany' },
    { label: 'Ghana', key: 'ghana' },
    { label: 'Greece', key: 'greece' },
    { label: 'Grenada', key: 'grenada' },
    { label: 'Guatemala', key: 'guatemala' },
    { label: 'Guinea', key: 'guinea' },
    { label: 'Guinea-Bissau', key: 'guinea-bissau' },
    { label: 'Guyana', key: 'guyana' },
    { label: 'Haiti', key: 'haiti' },
    { label: 'Honduras', key: 'honduras' },
    { label: 'Hungary', key: 'hungary' },
    { label: 'Iceland', key: 'iceland' },
    { label: 'India', key: 'india' },
    { label: 'Indonesia', key: 'indonesia' },
    { label: 'Iran', key: 'iran' },
    { label: 'Iraq', key: 'iraq' },
    { label: 'Ireland', key: 'ireland' },
    { label: 'Israel', key: 'israel' },
    { label: 'Italy', key: 'italy' },
    { label: 'Jamaica', key: 'jamaica' },
    { label: 'Japan', key: 'japan' },
    { label: 'Jordan', key: 'jordan' },
    { label: 'Kazakhstan', key: 'kazakhstan' },
    { label: 'Kenya', key: 'kenya' },
    { label: 'Kiribati', key: 'kiribati' },
    { label: 'Kuwait', key: 'kuwait' },
    { label: 'Kyrgyzstan', key: 'kyrgyzstan' },
    { label: 'Laos', key: 'laos' },
    { label: 'Latvia', key: 'latvia' },
    { label: 'Lebanon', key: 'lebanon' },
    { label: 'Lesotho', key: 'lesotho' },
    { label: 'Liberia', key: 'liberia' },
    { label: 'Libya', key: 'libya' },
    { label: 'Liechtenstein', key: 'liechtenstein' },
    { label: 'Lithuania', key: 'lithuania' },
    { label: 'Luxembourg', key: 'luxembourg' },
    { label: 'Madagascar', key: 'madagascar' },
    { label: 'Malawi', key: 'malawi' },
    { label: 'Malaysia', key: 'malaysia' },
    { label: 'Maldives', key: 'maldives' },
    { label: 'Mali', key: 'mali' },
    { label: 'Malta', key: 'malta' },
    { label: 'Marshall Islands', key: 'marshall-islands' },
    { label: 'Mauritania', key: 'mauritania' },
    { label: 'Mauritius', key: 'mauritius' },
    { label: 'Mexico', key: 'mexico' },
    { label: 'Micronesia', key: 'micronesia' },
    { label: 'Moldova', key: 'moldova' },
    { label: 'Monaco', key: 'monaco' },
    { label: 'Mongolia', key: 'mongolia' },
    { label: 'Montenegro', key: 'montenegro' },
    { label: 'Morocco', key: 'morocco' },
    { label: 'Mozambique', key: 'mozambique' },
    { label: 'Myanmar (Burma)', key: 'myanmar' },
    { label: 'Namibia', key: 'namibia' },
    { label: 'Nauru', key: 'nauru' },
    { label: 'Nepal', key: 'nepal' },
    { label: 'Netherlands', key: 'netherlands' },
    { label: 'New Zealand', key: 'new-zealand' },
    { label: 'Nicaragua', key: 'nicaragua' },
    { label: 'Niger', key: 'niger' },
    { label: 'Nigeria', key: 'nigeria' },
    { label: 'North Korea', key: 'north-korea' },
    { label: 'North Macedonia', key: 'north-macedonia' },
    { label: 'Norway', key: 'norway' },
    { label: 'Oman', key: 'oman' },
    { label: 'Pakistan', key: 'pakistan' },
    { label: 'Palau', key: 'palau' },
    { label: 'Palestine State', key: 'palestine-state' },
    { label: 'Panama', key: 'panama' },
    { label: 'Papua New Guinea', key: 'papua-new-guinea' },
    { label: 'Paraguay', key: 'paraguay' },
    { label: 'Peru', key: 'peru' },
    { label: 'Philippines', key: 'philippines' },
    { label: 'Poland', key: 'poland' },
    { label: 'Portugal', key: 'portugal' },
    { label: 'Qatar', key: 'qatar' },
    { label: 'Romania', key: 'romania' },
    { label: 'Russia', key: 'russia' },
    { label: 'Rwanda', key: 'rwanda' },
    { label: 'Saint Kitts and Nevis', key: 'saint-kitts-and-nevis' },
    { label: 'Saint Lucia', key: 'saint-lucia' },
    { label: 'Saint Vincent and the Grenadines', key: 'saint-vincent-and-the-grenadines' },
    { label: 'Samoa', key: 'samoa' },
    { label: 'San Marino', key: 'san-marino' },
    { label: 'Sao Tome and Principe', key: 'sao-tome-and-principe' },
    { label: 'Saudi Arabia', key: 'saudi-arabia' },
    { label: 'Senegal', key: 'senegal' },
    { label: 'Serbia', key: 'serbia' },
    { label: 'Seychelles', key: 'seychelles' },
    { label: 'Sierra Leone', key: 'sierra-leone' },
    { label: 'Singapore', key: 'singapore' },
    { label: 'Slovakia', key: 'slovakia' },
    { label: 'Slovenia', key: 'slovenia' },
    { label: 'Solomon Islands', key: 'solomon-islands' },
    { label: 'Somalia', key: 'somalia' },
    { label: 'South Africa', key: 'south-africa' },
    { label: 'South Korea', key: 'south-korea' },
    { label: 'South Sudan', key: 'south-sudan' },
    { label: 'Spain', key: 'spain' },
    { label: 'Sri Lanka', key: 'sri-lanka' },
    { label: 'Sudan', key: 'sudan' },
    { label: 'Suriname', key: 'suriname' },
    { label: 'Sweden', key: 'sweden' },
    { label: 'Switzerland', key: 'switzerland' },
    { label: 'Syria', key: 'syria' },
    { label: 'Tajikistan', key: 'tajikistan' },
    { label: 'Tanzania', key: 'tanzania' },
    { label: 'Thailand', key: 'thailand' },
    { label: 'Timor-Leste', key: 'timor-leste' },
    { label: 'Togo', key: 'togo' },
    { label: 'Tonga', key: 'tonga' },
    { label: 'Trinidad and Tobago', key: 'trinidad-and-tobago' },
    { label: 'Tunisia', key: 'tunisia' },
    { label: 'Turkey', key: 'turkey' },
    { label: 'Turkmenistan', key: 'turkmenistan' },
    { label: 'Tuvalu', key: 'tuvalu' },
    { label: 'Uganda', key: 'uganda' },
    { label: 'Ukraine', key: 'ukraine' },
    { label: 'United Arab Emirates', key: 'united-arab-emirates' },
    { label: 'United Kingdom', key: 'united-kingdom' },
    { label: 'United States of America', key: 'united-states' },
    { label: 'Uruguay', key: 'uruguay' },
    { label: 'Uzbekistan', key: 'uzbekistan' },
    { label: 'Vanuatu', key: 'vanuatu' },
    { label: 'Vatican City', key: 'vatican-city' },
    { label: 'Venezuela', key: 'venezuela' },
    { label: 'Vietnam', key: 'vietnam' },
    { label: 'Yemen', key: 'yemen' },
    { label: 'Zambia', key: 'zambia' },
    { label: 'Zimbabwe', key: 'zimbabwe' },
  ];
  